version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/app/src

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./server/src:/app/src

  nginx:
    volumes:
      - './nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf'
